services:
  load_balancer:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/app
      - /etc/letsencrypt:/etc/letsencrypt/

    network_mode: 'host'